### ISSUE TITLE
gopy: prepare support for Windows/Darwin

### ISSUE THREAD

**Issue by sbinet** [go-python/gopy#101]
to not make porting to Windows/Darwin too much of a hassle we should prepare for it and abstract away some of the linux-isms that are sprinkled in `gopy`'s codebase:

- replace `".so"` with a `const dllExt = "..."` (and have that `dllExt` constant be defined in properly OS-guarded files)
- replace calls to `/bin/cp` with pure-Go versions
- replace `pkg-config` with *something* on Windows
- others ?

**Comment by corona10** [comment]
This https://github.com/go-python/gopy/issues/72 issue will happen on Windows as well.
AFAIK More bad thing is that `pkg-config` is not built in on the Windows.

**Comment by sbinet** [comment]
right. thanks. (updated the list above)

**Comment by ThePlasmaRailgun** [comment]
I'm attempting to compile https://github.com/divan/txqr and I can say for sure that the lack of windows support is hurting right now. I installed both the go package pkg-config and the unix executable pkg-config and neither worked. At this point I'm pretty much lost.

**Comment by sbinet** [comment]
could you try specifying the `cffi` backend? this one shouldn't need `pkg-config`, IIRC.

**Comment by ThePlasmaRailgun** [comment]
CFFI backend seemed to work to generate it, I'll try importing to see if that works too

**Comment by ThePlasmaRailgun** [comment]
Ah, no, sorry, it throws an error about gcc. Do I need a go-specific GCC or just the regular one from something like MinGW?

**Comment by ThePlasmaRailgun** [comment]
Installed the MinGW one, 
```# runtime/cgo
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
2019/01/08 15:19:28 error dispatching command: exit status 2```

**Comment by ThePlasmaRailgun** [comment]
Fixed that, now I get 
```# runtime/cgo
gcc_libinit_windows.c: In function 'x_cgo_sys_thread_create':
gcc_libinit_windows.c:56:12: error: implicit declaration of function '_beginthread'; did you mean 'OpenThread'? [-Werror=implicit-function-declaration]
  thandle = _beginthread(func, 0, arg);
            ^~~~~~~~~~~~
            OpenThread
cc1: all warnings being treated as errors
2019/01/08 15:36:30 error dispatching command: exit status 2

C:\Users\finian_blackett\Documents>```

I'm using MinGW-w64 with the version `x86_64-8.1.0-win32-seh-rt_v6-rev0`

**Comment by sbinet** [comment]
Thanks. I'll try to setup an AppVeyor CI test to advance the Windows support.
I'll try to do that by the end of the week.

**Comment by rcoreilly** [comment]
for old version, closing
