### ISSUE TITLE
panic: could not look-up "interface{}"

### ISSUE THREAD

**Issue by zhangdong046** [go-python/gopy#107]
Is this a bug in platform (go version go1.8 linux/amd64).

**Comment by zhangdong046** [comment]
Cannot get sample maps working under Go 1.8.
for details: 
maps.MapsFunc({"1":"2"})
panic: runtime error: invalid memory address or nil pointer dereference

**Comment by zhangdong046** [comment]
Cannot get sample maps working under Go 1.5.3 too

**Comment by sbinet** [comment]
hi,
could you provide instructions (code, commands, ...) so we can reproduce the error you encountered?
it's a bit hard to know what happened otherwise :)

**Comment by zhangdong046** [comment]
It is like 
    func (this *T) Test(a []string) {}
or
    func (this *T) Test(a ...string) {}
or 
    func(this *T) Test(a interface{}){}
is these usage is not supported?

**Comment by sbinet** [comment]
yes, `interface{}`s are not supported yet (in any backend, FWIW)

variadic functions are also a bit of a sorry state as well.

slices of strings ok though, but the mapping of a tuple or list of python strings to a Go slice of strings is missing (the `gopy` layer would need at some point to validate the type of each of the `PyObject`s in the `PyList` or `PyTuple` to be of type `PyString`.)

easiest workaround I could find is the following:

```python
>>> import slices
>>> s = slices.New()
>>> s.Data
<[]string object at 0x7f248ef74150>
>>> s.Append("v")
>>> s.Append("d")
>>> s.Data
<[]string object at 0x7f248ef74130>
>>> s.Data[0]
'v'
>>> s.Data[1]
'd'
>>> slices.Func(s.Data)
Func([v d])
```

where the `slices` module is in fact this Go package:

```go
package slices

import "fmt"

func Func(a []string) {
	fmt.Printf("Func(%v)\n", a)
}

type Slice struct {
	Data []string
}

func New() Slice {
	return Slice{}
}

func (s *Slice) Append(v string) {
	s.Data = append(s.Data, v)
}
```

**Comment by zhangdong046** [comment]
thanks, I do understand now.
