### ISSUE TITLE
gopy: go-1.9 requires exactly one main package for c-shared libs

### ISSUE THREAD

**Issue by sbinet** [go-python/gopy#108]
we need to tackle this issue:

https://travis-ci.org/go-python/gopy/jobs/247165038

```
=== RUN   TestPyErrors
-buildmode=c-shared requires exactly one main package
2017/06/26 16:08:45 error dispatching command: exit status 1
--- FAIL: TestBindConsts (0.30s)
	main_test.go:68: [_examples/consts]: error running gopy-bind: exit status 1
```

**Comment by corona10** [comment]
@sbinet 
Something happening on the Go main repository.
I read their code reviewing system.
https://go-review.googlesource.com/c/46421/
This is an impressive comment.
>> To be clear, I don't really know what I'm doing.


Hmm is there any solution to solve this issue?
Now it looks like same as `-buildmode=c-archive`.

**Comment by corona10** [comment]
Related our code line: 
https://github.com/go-python/gopy/blob/master/cmd_bind.go#L84
