### ISSUE TITLE
Is this project ready to use ?

### ISSUE THREAD

**Issue by Huarong** [go-python/gopy#140]
It seems the development is not active.
So what is the status of the project?  Can we use it in production?

**Comment by corona10** [comment]
@Huarong 
Development is active. 
If you want to use it. You need to set `cgocheck=0`.
If you want to use goroutine on Python by using gopy.
[Here](http://corona10.github.io/GSoC2017-Week1/) is the easy way example.

**Comment by Huarong** [comment]
Thank you.  I'll try later. Hope this can work.

**Comment by sbinet** [comment]
Hi,
As Dong-hee told you, the development is still active (and with the last commit being last week...)

What gave you the impression it wasn't active?
(So we can fix this)

**Comment by corona10** [comment]
@sbinet 
Maybe we need to open WIP pull request :)

**Comment by Huarong** [comment]
@sbinet There is no release and no version. I do not know how far it is from being used in production.

Or it is just a toy project?  We can not tell from the README.

**Comment by rcoreilly** [comment]
now definitely working! :)
