### ISSUE TITLE
how to run a callback function of python?

### ISSUE THREAD

**Issue by nilday** [go-python/gopy#144]
I'm trying to implement some function like  map or filter in go which will take a function as an input.
For example:

```python
def append(x):
    return x + "append"

go_list=['a','b','c']# assume this is a go object
go_list.map(append) # will return ['aappend','bappend','cappend']
```

or filter function like:
```python
go_list=[1,2,3]
go_list.filter(lambda x: return x>1) # will return [2,3]
```

It is to say: how to pass a python function to go , and use go to callback?

**Comment by sbinet** [comment]
IIRC, this isn't yet supported.

the first example should be rather easy to implement.
the second one could be a bit trickier to do (but who knows.)

**Comment by rcoreilly** [comment]
now supported in new version.
