### ISSUE TITLE
Building with Go 1.10

### ISSUE THREAD

**Issue by abourget** [go-python/gopy#155]
Hi there,

I'm trying to build a quite simple binding and ran into these issues:

```
$ gopy bind -work=true -lang=py2 -output=./bin github.com/mulesoft-labs/amf-core/cmd/amfpy
2018/03/15 17:00:52 work: /tmp/gopy-052348342
go build _/tmp/gopy-052348342: invalid pkg-config package name: --cflags
```

I checked and found that `go build`  looped through the params listed here: 
```go
		for _, pkg := range pkgs {
			if !load.SafeArg(pkg) {
				return nil, nil, fmt.Errorf("invalid pkg-config package name: %s", pkg)
			}
		}
```
> ref: https://github.com/golang/go/blob/master/src/cmd/go/internal/work/exec.go#L953

where `pkgs` is:

```go
[]string{"python-2.7", "--cflags", "--libs"}
```

```go
// File is generated by gopy gen. Do not edit.
package main
//#cgo pkg-config: %[2]s --cflags --libs               <--- this line
//#include <stdlib.h>
//#include <string.h>
```
> ref: https://github.com/go-python/gopy/blob/master/bind/gengo.go#L51

When I remove `--cflags --libs` from the `gengo.go` file, my program compiled correctly.

Since I don't understand all the intricacies of `cgo`.. I'm just asking if it's worth me whipping up a PR for this ?

**Comment by abourget** [comment]
For ref: https://github.com/abourget/gopy/commit/977252b0c0a2071c4e25addb919bafda1647c011

**Comment by sbinet** [comment]
SGTM

you might want to also add `1.10.x` to `.travis.yml` :)
