### ISSUE TITLE
cffi: invalid syntax for slices in generated Python

### ISSUE THREAD

**Issue by initialed85** [go-python/gopy#156]
Hi guys,

Firstly- awesome tool, we're using it in production to wrap up soniah/gosnmp and x/golang.org/ssh for use by Python and it works a treat.

I've noted a problem with some of the Python generated for CFFI when it comes to slices.

Platform details are:

	Darwin theophilus.ftpsolutions.com.au 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64 (MacOS)

	go version go1.10 darwin/amd64

	Python 2.7.14 (default, Mar 15 2018, 15:54:45)
	[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin

	Python 2.7.13 (0e7ea4fe15e82d5124e805e2e4a37cae1a402d4b, Jan 06 2018, 12:46:49)
	[PyPy 5.10.0 with GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin

The code I'm playing with is the "attempt1" folder in the following repo:

https://github.com/initialed85/golang_python_binding_research

In summary, for a struct that looks as follows:

	type OneWithTheLot struct {
		SomeString        string
		SomeInt           int64
		SomeFloat         float64
		SomeBool          bool
		SomeListOfStrings []string
		SomeListOfInts    []int64
		SomeListOfFloats  []float64
		SomeListOfBools   []bool
	}

And a build command as follows:

    ./gopy bind -lang="cffi" -output="src/$PACKAGE/cffi" -symbols=true -work=false $PACKAGE

The following code is generated for CFFI in the Python file (truncated):

    if py_kwd_005 != None:
        if not isinstance(py_kwd_005, []str): // replace with list to fix
            raise TypeError("invalid type for 'SomeListOfStrings' attribute")
        c_kwd_005 = _cffi_helper.cffi_cgopy_cnv_py2c_0x3827357999(py_kwd_005)
        _cffi_helper.lib.cgo_func_attempt1_OneWithTheLot_setter_5(self.cgopy, c_kwd_005)
    py_kwd_006 = None
    if  5 < nargs:
        py_kwd_006 = args[5]
    if "SomeListOfInts" in kwargs:
        py_kwd_006 = kwargs["SomeListOfInts"]
    if py_kwd_006 != None:
        if not isinstance(py_kwd_006, []long): // replace with list to fix
            raise TypeError("invalid type for 'SomeListOfInts' attribute")
        c_kwd_006 = _cffi_helper.cffi_cgopy_cnv_py2c_0x1193098013(py_kwd_006)
        _cffi_helper.lib.cgo_func_attempt1_OneWithTheLot_setter_6(self.cgopy, c_kwd_006)
    py_kwd_007 = None
    if  6 < nargs:
        py_kwd_007 = args[6]
    if "SomeListOfFloats" in kwargs:
        py_kwd_007 = kwargs["SomeListOfFloats"]
    if py_kwd_007 != None:
        if not isinstance(py_kwd_007, []float): // replace with list to fix
            raise TypeError("invalid type for 'SomeListOfFloats' attribute")
        c_kwd_007 = _cffi_helper.cffi_cgopy_cnv_py2c_0x3325242294(py_kwd_007)
        _cffi_helper.lib.cgo_func_attempt1_OneWithTheLot_setter_7(self.cgopy, c_kwd_007)
    py_kwd_008 = None
    if  7 < nargs:
        py_kwd_008 = args[7]
    if "SomeListOfBools" in kwargs:
        py_kwd_008 = kwargs["SomeListOfBools"]
    if py_kwd_008 != None:
        if not isinstance(py_kwd_008, []bool): // replace with list to fix
            raise TypeError("invalid type for 'SomeListOfBools' attribute")
        c_kwd_008 = _cffi_helper.cffi_cgopy_cnv_py2c_0x1259315698(py_kwd_008)
        _cffi_helper.lib.cgo_func_attempt1_OneWithTheLot_setter_8(self.cgopy, c_kwd_008)

Simply changing the four bolded pieces of text to "list" results in perfectly working Python.

I've worked around this for now with a few nasty ```sed``` commands, for awareness they are:

	sed 's/\[\]str):/list):/g' src/$PACKAGE/cffi/$PACKAGE.py > $TEMP_FILE
	mv $TEMP_FILE src/$PACKAGE/cffi/$PACKAGE.py

	sed 's/\[\]int):/list):/g' src/$PACKAGE/cffi/$PACKAGE.py > $TEMP_FILE
	mv $TEMP_FILE src/$PACKAGE/cffi/$PACKAGE.py

	sed 's/\[\]long):/list):/g' src/$PACKAGE/cffi/$PACKAGE.py > $TEMP_FILE
	mv $TEMP_FILE src/$PACKAGE/cffi/$PACKAGE.py

	sed 's/\[\]float):/list):/g' src/$PACKAGE/cffi/$PACKAGE.py > $TEMP_FILE
	mv $TEMP_FILE src/$PACKAGE/cffi/$PACKAGE.py

	sed 's/\[\]bool):/list):/g' src/$PACKAGE/cffi/$PACKAGE.py > $TEMP_FILE
	mv $TEMP_FILE src/$PACKAGE/cffi/$PACKAGE.py

When I get a bit of time I'll try to pull the gopy repo down and get it all building and see if I can't help- no promises though, I'm pretty new to Go.

**Comment by sbinet** [comment]
@corona10 do you want to tacke this ?

**Comment by corona10** [comment]
Sure

**Comment by corona10** [comment]
@sbinet I submitted a CL.

**Comment by sbinet** [comment]
Fixed by #158
