### ISSUE TITLE
Strange behaviour with Python's multiprocessing (possibly fork() related?)

### ISSUE THREAD

**Issue by initialed85** [go-python/gopy#157]
Hi guys,

I've noticed a problem that arises when using Python modules built by gopy with Python's "multiprocessing" module.

Native platform is:

	Darwin theophilus.ftpsolutions.com.au 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

	Python 2.7.14 (default, Mar 15 2018, 15:54:45)
	[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin

	Python 2.7.13 (0e7ea4fe15e82d5124e805e2e4a37cae1a402d4b, Jan 06 2018, 12:46:49)
	[PyPy 5.10.0 with GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

	go version go1.10 darwin/amd64

And Linux (Ubuntu in Docker) platform is:

	Linux e023cfd81209 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

	Python 2.7.12 (default, Dec  4 2017, 14:50:18)
	[GCC 5.4.0 20160609] on linux2

	Python 2.7.13 (0e7ea4fe15e8, Dec 22 2017, 08:44:03)
	[PyPy 5.10.0 with GCC 6.2.0 20160901] on linux2

	go version go1.9 linux/amd64

The code is in "attempt4" at the following repo:

https://github.com/initialed85/golang_python_binding_research

The Go side has a simple function that looks like this:

	func DoSomething() string {
		fmt.Println("Before doing something")
		time.Sleep(time.Second)
		fmt.Println("After doing something")

		return "Okay, I did it"
	}

And the Python side looks like this:

	import time
	from multiprocessing import Process

	from src.attempt4 import DoSomething

	print 'Doing something in a process'
	p = Process(target=DoSomething)
	p.start()
	time.sleep(2)
	p.join()

I see slightly different behaviour between MacOS and Ubuntu in Docker.

**MacOS - Python**

    (golang_python_binding_research_py2) theophilus:golang_python_binding_research edwardbeech$ GODEBUG=cgocheck=0 python attempt4.py
    Doing something in a process
    before doing something
    mach error semaphore_signal: 15
    fatal error: mach error

    runtime stack:
    runtime.throw(0x10d3e1921, 0xa)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:619 +0x81
    runtime.macherror(0x10000000f, 0x10d3e261e, 0x10)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/os_darwin.go:224 +0xa3
    runtime.mach_semrelease.func1()
        /usr/local/Cellar/go/1.10/libexec/src/runtime/os_darwin.go:477 +0x3d
    runtime.mach_semrelease(0x7ffe00002403)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/os_darwin.go:477 +0x45
    runtime.semawakeup(0xc420072000)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/os_darwin.go:36 +0x21
    runtime.notewakeup(0xc420072148)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/lock_sema.go:147 +0x59
    runtime.startm(0x0, 0xc420000101)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:2012 +0xda
    runtime.wakep()
        /usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:2078 +0x48
    runtime.newproc1(0x10d3e8090, 0xc420054d58, 0x100000008, 0x10d35a7a7)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:3343 +0x314
    runtime.newproc.func1()
        /usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:3239 +0x46
    runtime.systemstack(0x7ffee2d236c0)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:409 +0x79
    runtime.mstart()
        /usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:1170

    goroutine 17 [running, locked to thread]:
    runtime.systemstack_switch()
        /usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:363 fp=0xc420054d08 sp=0xc420054d00 pc=0x10d365f90
    runtime.newproc(0xc400000008, 0x10d3e8090)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:3238 +0x64 fp=0xc420054d48 sp=0xc420054d08 pc=0x10d348f74
    runtime.(*timersBucket).addtimerLocked(0x10d4644e0, 0xc4200a8080)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/time.go:160 +0x107 fp=0xc420054da0 sp=0xc420054d48 pc=0x10d35a7a7
    time.Sleep(0x3b9aca00)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/time.go:101 +0x135 fp=0xc420054e00 sp=0xc420054da0 pc=0x10d35a535
    attempt4.DoSomething(0x0, 0xc420054e88)
        /Users/edwardbeech/Projects/Home/golang_python_binding_research/src/attempt4/attempt4.go:17 +0x6e fp=0xc420054e60 sp=0xc420054e00 pc=0x10d3abc2e
    main.cgo_func_attempt4_DoSomething(0xc400000008, 0x10d3e7c80)
        /private/var/folders/j1/b2w166dj3hx8fn68q1ys0r740000gn/T/gopy-209737331/attempt4.go:167 +0x22 fp=0xc420054e80 sp=0xc420054e60 pc=0x10d3ade12
    main._cgoexpwrap_0d8f056a40e9_cgo_func_attempt4_DoSomething(0x0, 0x0)
        _cgo_gotypes.go:219 +0x50 fp=0xc420054ea8 sp=0xc420054e80 pc=0x10d3ad460
    runtime.call32(0x0, 0x7ffee2d23710, 0x7ffee2d237a8, 0x10)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:573 +0x3b fp=0xc420054ed8 sp=0xc420054ea8 pc=0x10d36635b
    runtime.cgocallbackg1(0x0)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/cgocall.go:316 +0x19c fp=0xc420054f58 sp=0xc420054ed8 pc=0x10d31a7bc
    runtime.cgocallbackg(0x0)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/cgocall.go:194 +0xda fp=0xc420054fc0 sp=0xc420054f58 pc=0x10d31a58a
    runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:826 +0x9b fp=0xc420054fe0 sp=0xc420054fc0 pc=0x10d36792b
    runtime.goexit()
        /usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420054fe8 sp=0xc420054fe0 pc=0x10d368a61
    (golang_python_binding_research_py2) theophilus:golang_python_binding_research edwardbeech$

**MacOS - PyPy**

	(golang_python_binding_research_pypy) theophilus:golang_python_binding_research edwardbeech$ GODEBUG=cgocheck=0 python attempt4.py
    WARNING: PyPy detected- be prepared for very odd behaviour
    Doing something in a process
    before doing something
    mach error semaphore_signal: 15
    fatal error: mach error

    runtime stack:
    runtime.throw(0x109246901, 0xa)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:619 +0x81
    runtime.macherror(0x10000000f, 0x1092475fe, 0x10)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/os_darwin.go:224 +0xa3
    runtime.mach_semrelease.func1()
        /usr/local/Cellar/go/1.10/libexec/src/runtime/os_darwin.go:477 +0x3d
    runtime.mach_semrelease(0x7ffe00000e03)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/os_darwin.go:477 +0x45
    runtime.semawakeup(0xc420046800)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/os_darwin.go:36 +0x21
    runtime.notewakeup(0xc420046948)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/lock_sema.go:147 +0x59
    runtime.startm(0x0, 0xc420000101)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:2012 +0xda
    runtime.wakep()
        /usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:2078 +0x48
    runtime.newproc1(0x10924d070, 0xc420054d58, 0x100000008, 0x1091bf8f7)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:3343 +0x314
    runtime.newproc.func1()
        /usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:3239 +0x46
    runtime.systemstack(0x7ffeea083d90)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:409 +0x79
    runtime.mstart()
        /usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:1170

    goroutine 17 [running, locked to thread]:
    runtime.systemstack_switch()
        /usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:363 fp=0xc420054d08 sp=0xc420054d00 pc=0x1091cb0e0
    runtime.newproc(0xc400000008, 0x10924d070)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:3238 +0x64 fp=0xc420054d48 sp=0xc420054d08 pc=0x1091ae0c4
    runtime.(*timersBucket).addtimerLocked(0x1092c93e0, 0xc420020100)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/time.go:160 +0x107 fp=0xc420054da0 sp=0xc420054d48 pc=0x1091bf8f7
    time.Sleep(0x3b9aca00)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/time.go:101 +0x135 fp=0xc420054e00 sp=0xc420054da0 pc=0x1091bf685
    attempt4.DoSomething(0x0, 0xc420054e88)
        /Users/edwardbeech/Projects/Home/golang_python_binding_research/src/attempt4/attempt4.go:17 +0x6e fp=0xc420054e60 sp=0xc420054e00 pc=0x109210d7e
    main.cgo_func_attempt4_DoSomething(0xc400000008, 0x10924cc60)
        /private/var/folders/j1/b2w166dj3hx8fn68q1ys0r740000gn/T/gopy-299733581/attempt4.go:167 +0x22 fp=0xc420054e80 sp=0xc420054e60 pc=0x109212f62
    main._cgoexpwrap_3134bae50931_cgo_func_attempt4_DoSomething(0x0, 0x0)
        _cgo_gotypes.go:219 +0x50 fp=0xc420054ea8 sp=0xc420054e80 pc=0x1092125b0
    runtime.call32(0x0, 0x7ffeea083de0, 0x7ffeea083e78, 0x10)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:573 +0x3b fp=0xc420054ed8 sp=0xc420054ea8 pc=0x1091cb4ab
    runtime.cgocallbackg1(0x0)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/cgocall.go:316 +0x19c fp=0xc420054f58 sp=0xc420054ed8 pc=0x10917f90c
    runtime.cgocallbackg(0x0)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/cgocall.go:194 +0xda fp=0xc420054fc0 sp=0xc420054f58 pc=0x10917f6da
    runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:826 +0x9b fp=0xc420054fe0 sp=0xc420054fc0 pc=0x1091cca7b
    runtime.goexit()
        /usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420054fe8 sp=0xc420054fe0 pc=0x1091cdbb1
    (golang_python_binding_research_pypy) theophilus:golang_python_binding_research edwardbeech$

**Ubuntu in Docker - Python**

    (python) root@e023cfd81209:~/golang_python_binding_research# GODEBUG=cgocheck=0 python attempt4.py
    Doing something in a process
    Before doing something

At that point it blocks forever.

**Ubuntu in Docker - PyPy**

    (pypy) root@e023cfd81209:~/golang_python_binding_research# GODEBUG=cgocheck=0 python attempt4.py
    WARNING: PyPy detected- be prepared for very odd behaviour
    Doing something in a process
    Before doing something

This one also blocks forever.

**Comment by sbinet** [comment]
yeah... multiprocessing forks itself ([fork(3)](https://linux.die.net/man/3/fork)) and leverages Copy-On-Write to achieve good performances.

but a Go program or library is - at its core - a (possibly heavily) multithreaded beast.
this is famously hard to make cohabit the two: forking+multithreading (because you could very well have the program fork itself while a lock is being held, leaving one of the two sides, the child or the parent, deadlocking, or forking while a thread is in a critical section, etc... etc...)

I am not sure there's any workable path or workaround for this issue...

**Comment by initialed85** [comment]
I was able to work around it in a less-than-ideal way; if the child process is the first thing to import the Go module then it all works (as long as you haven't already imported the module in the parent process).

I think this is because a new Go runtime is allocated for each child process, but I'm not sure.

Naturally it's going to have limited usefulness (e.g. if you need state that's established on the Go side or whatever) but it at least sort of permits the user to make use a Go module in their Python multiprocess'd application.

Example code is in my test repo, it's the "attempt5" stuff.

https://github.com/initialed85/golang_python_binding_research/

**Comment by lemurchik** [comment]
Hi guys,

Do you have a solution for this problem?

**Comment by rcoreilly** [comment]
per @sbinet's comments, this is likely unfixable, but in any case, if you want to pursue it, give a try with the new version -- it is possible with the `exe` mode to start things on the Go side before launching python, in case that might help -- was key for getting GUI running properly.  Anyway, file a new issue if still relevant.
