### ISSUE TITLE
handling of packages using other packages' types or values

### ISSUE THREAD

**Issue by sbinet** [go-python/gopy#18]
consider:

``` go
// pkg1/pk1.go
package pkg1

const C = 42
var V = 42
type T struct {}
```

and:

``` go
// pkg2/pkg2.go
package pkg2

import ( 
    "github.com/some/pkg1"
)

func NewT() pkg1.T {...}
```

what should `gopy` do?
- pull in the whole `pkg1` package and wrap it as part of `pkg2.so` ?
- wrap `pkg2.NewT` and return a `PyObject`/`PyDict`? an opaque `PyCObject` ?
- wrap `pkg2.NewT` and return a `PyCapsule` ?
- bail out ?
- something else ?

https://docs.python.org/2/c-api/capsule.html#capsules

**Comment by rcoreilly** [comment]
for old version, closing
