### ISSUE TITLE
mojave10.14.5 fatal error: 'bufferobject.h' file not found

### ISSUE THREAD

**Issue by hucs2542** [go-python/gopy#189]
# _/private/var/folders/1x/fm6my0h10g12cf035fszn64m0000gn/T/gopy-217996282
hi.c:15:10: fatal error: 'bufferobject.h' file not found
2019/07/18 00:51:47 error dispatching command: could not generate build command: exit status 2

**Comment by rcoreilly** [comment]
refile if still relevant
