### ISSUE TITLE
Questions that I can't find answers about Gopy

### ISSUE THREAD

**Issue by ghost** [go-python/gopy#201]
Hi all,

I'm a Windows 10 user.

I have a few questions, can you answer them?

1. What we need to install to use Gopy on Windows **(what should be 32/64 gcc, python, go, msbuild tools)**
I get the error "%1 is not a valid win32 application".

2. Is it correct to use Gopy for speed?
Obviously I don't like c ++ and c, they seem confused to me.
I don't understand Cython after a level.
I couldn't answer this question because I couldn't try it, I couldn't find anything in Readme.

3. Gopy seems to appeal to advanced users.
The explanations are very short and not understandable.
Wouldn't a detailed wiki be great for installation and use?
Maybe when you have solved all the problems of the project, you think of something like that, I couldn't see it.

I'm sure the questions I ask come to the minds of other people who are curious about Gopy.

Would you consider adding a few things to readme to meet expectations and curiosities?

Cheers

**Comment by rcoreilly** [comment]
1. I don't use windows and haven't tried it there, but I agree we should have more information on what it takes and a detailed tutorial for getting it working there.  On mac and linux it pretty much just works with standard installs.

2. There aren't any formal benchmarks that I know of but it *should* be as fast as typical python bindings to C++, as pybindgen is widely used.  I have used it for my neural network simulations and it is not obviously slow in any way.

3. Good idea for wiki -- I have a more detailed README here: https://github.com/goki/gi/tree/master/python which I can add to wiki when I get a chance.

**Comment by sbinet** [comment]
to add to what @rcoreilly already said, Windows is already tested _via_ Appveyor:
- https://ci.appveyor.com/project/sbinet/gopy/history

and here is what is used to test on Windows:
- https://github.com/go-python/gopy/blob/master/appveyor.yml#L24

**Comment by destroyersboy** [comment]
> '%GOPATH%\bin;%CPYTHON2DIR%;%CPYTHON2DIR%\\Scripts;%CPYTHON3DIR%;%CPYTHON3DIR%\\Scripts;C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%'

Everything in this file is attached to the path.
It's not just as the locations wrote here.
God, this is so bad.

There is nothing different in the makefile Gopy created.
If msys2 is able to run the makefile, maybe I can change the values ​​in it, gcc parameters, and a few things.
But I could not find anything to run makefile in Windows.

**Comment by rcoreilly** [comment]
windows now working much better -- file new issues..
