### ISSUE TITLE
add option to suppress warnings

### ISSUE THREAD

**Issue by rcoreilly** [go-python/gopy#219]
Should getting warnings about incompatible things be opt-in or opt-out -- probably opt-out I guess?  e.g., add a --no-warn flag or something to that effect?

I'm just running on GoGi with latest gopy version, and 5266c83 results in a massive number of "ignoring python incompatible method.." messages, which are expected and not something I'm going to change in the Go code.

@cosnicolaou @sbinet any thoughts?

**Comment by sbinet** [comment]
SGTM

**Comment by cosnicolaou** [comment]
sure, that makes sense.
