### ISSUE TITLE
Can't run examples on Mac.

### ISSUE THREAD

**Issue by RomanKoshkin** [go-python/gopy#227]
I am using Python 3.7.3 (Anaconda). I run
`gopy build -output=out proj1`

and get this output (see below). It should use python 3.7 (not 2.7).

> (base) Romans-MacBook-Pro:src romankoshkin$ gopy build -output=out proj1
> 
> --- Processing package: proj1 ---
> 
> --- building package ---
> gopy build -output=out proj1
> goimports -w hello.go
> go build -buildmode=c-shared -o hello_go.so .
> python build.py
> go run patch-leaks.go hello.c # patch memory leaks in pybindgen output
> go env CC
> python-config --cflags
> python-config --ldflags
> clang hello.c -dynamiclib hello_go.so -o _hello.so -I/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -L/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -ldl -framework CoreFoundation -fPIC --shared -Ofast

At the same time, if I look into `Makefile`, I see

> CFLAGS = -I/anaconda3/include/python3.7m
> LDFLAGS = -L//anaconda3/lib -lpython3.7m -ldl  -framework CoreFoundation 

Which is what should be there (since I'm on Python3). When I try to import the hello package into python, it gives me the error:

>  import hello
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/romankoshkin/go/src/out/hello.py", line 12, in <module>
>     import _hello
> ImportError: dynamic module does not define module export function (PyInit__hello)
> >>> 
 
And, finally, as was recommended in issue #195

I run 
`make build` which gives the following output:

>  build target builds the generated files -- this is what gopy build does..
>  this will otherwise be built during go build and may be out of date
> rm hello.c
>  goimports is needed to ensure that the imports list is valid
> goimports -w hello.go
> generate hello_go.so from hello.go -- the cgo wrappers to go functions
> go build -buildmode=c-shared -o hello_go.so hello.go
> use pybindgen to build the hello.c file which are the CPython wrappers to cgo wrappers..
> note: pip install pybindgen to get pybindgen if this fails
> /anaconda3/bin/python build.py
> patch storage leaks in pybindgen output
> go run patch-leaks.go hello.c
> build the _hello.so library that contains the cgo and CPython wrappers
> generated hello.py python wrapper imports this c-code package
> clang hello.c -dynamiclib hello_go.so -o _hello.so -I/anaconda3/include/python3.7m 
> -L//anaconda3/lib -lpython3.7m -ldl  -framework CoreFoundation  -fPIC --shared -w

But when I import `hello`, I get another error:

> import hello
> Segmentation fault: 11

What's the problem here?

**Comment by liuzl** [comment]
I have exactly the same problem.

**Comment by rcoreilly** [comment]
I'm pretty sure the issue here is not specifying -vm=python3 -- that is essential on mac.  will add a troubleshooting note.

**Comment by celsiusnarhwal** [comment]
I am having this same issue, and specifying `-vm=python3` did not resolve it.
