### ISSUE TITLE
output: .c: file not recognized: File format not recognized

### ISSUE THREAD

**Issue by GaudiestTooth17** [go-python/gopy#240]
I have Go code in `~/go/src/gopy-test`. When I'm in this folder and run `gopy pkg -vm="python3" gopy-test/`, I get this error:

`gopy: skipping 'main' package "gopy-test"

--- building package ---
gopy pkg -vm=python3 gopy-test/
goimports -w .go
go build -buildmode=c-shared -o _go.so .
python3 build.py
go run patch-leaks.go .c # patch memory leaks in pybindgen output
go env CC
gcc .c _go.so -o _.so -I/usr/include/python3.6m -L/usr/lib -lpython3.6m -lpthread -ldl -lutil -lm -fPIC --shared -Ofast
cmd had error: exit status 1
output: .c: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status

2021/02/12 15:47:25 error dispatching command: exit status 1`

I get the feeling that I might be misusing gopy, but I can't figure out exactly how.

**Comment by rcoreilly** [comment]
you now need to specify a full go.mod package path, so `gopy-test/` isn't correct.  open new issues if you encounter additional difficulties.
