### ISSUE TITLE
Can not pass python class name to golang.

### ISSUE THREAD

**Issue by sukeyisme** [go-python/gopy#253]
```golang
type A struct{

}
func FunA(cls interface{}){
 //lazy instantiation
  t :=reflect.TypeOf(cls)
  reflect.New(cls)
 // ...
}
```

```python
class Test(A):
  def fun(self):
     pass

FunA(Test)
````

AttributeError: type object 'Test' has no attribute 'handle'

**Comment by rcoreilly** [comment]
you are passing a derived python type to the go function -- the go function needs an instantiated instance of a go type.

e.g., 

```Python
Test = A()
FunA(Test)
```
should work.

`A` in python is just a python wrapper class, so it is possible to make derivatives of it in Python, but you can only ever pass the original A type back to go -- e.g., the __init__ code for A creates a go instance of A, and that is its handle, so you can pass that handle to FunA.

**Comment by rcoreilly** [comment]
in other words, it is impossible for Go to know about new Ptyhon types.

**Comment by sukeyisme** [comment]
ok,but i want to lazy instantiation class Test in golang side,may be impossiable.

**Comment by rcoreilly** [comment]
it is doable -- look at the `__init__` code generated for the python `A` type -- you just want to do the lazy instantiation on the *python* side, not the Go side, calling the proper Go method to make the new instance, not using reflect.

**Comment by sukeyisme** [comment]
No,i want lazy instantiation in golang side ,Because all my main code in golang side,python code ,only def some function.
And have any method call python function from golang.

**Comment by rcoreilly** [comment]
you can just have 1 function call at start of all your python-side functions that handles the lazy instantiation -- python should be able to handle all the reflect-style issues and the field is always called `handle` so presumably you can figure out a good way to make it work.  but it is not possible to pass a `nil` object to go and expect it to figure out the type -- the go side needs an already-instantiated object.

**Comment by sukeyisme** [comment]
Ok,i'll try this. 
```golang
type A struct{}
func (a *A) Fun(){
fmt.Println("golang side called")
}
type IFUN interface{
     Fun()
}
func FunTest(i IFUN){
  i.Fun()
}
```
```python
class A(B):
  def Fun(self):
    print("python side called")

a = A()
FunTest(a)
```
Another question,can python side be called? Thanks.

**Comment by rcoreilly** [comment]
Nope, only Python calls Go, not the other way.
