### ISSUE TITLE
'sed' is not recognized as an internal or external command...

### ISSUE THREAD

**Issue by astrelsky** [go-python/gopy#266]
sed is not a windows utility and shouldn't be used. I had to build in git bash after handling a handful of other issues to get a package to build. Why not just use python to do it?

**Comment by Keithcat1** [comment]
I also have this error.
C:\python\python.exe build.py
Doing windows sed hack to fix declspec for PyInit
cmd had error: exec: "sed": executable file not found in %PATH%

**Comment by samufi** [comment]
Quick fix: install [sed from GnuWin32](https://gnuwin32.sourceforge.net/packages/sed.htm) and add it to the `PATH`. However, this should not be necessary. A simple search and replace can be done with Windows tools as well or from Python.

**Comment by sbinet** [comment]
or from Go :)
