### ISSUE TITLE
Flag provided but not defined 

### ISSUE THREAD

**Issue by cxloe** [go-python/gopy#271]
When trying to build the example i get:
"./gopy -vm=python3 build github.com/go-python/gopy/_examples/hi 
flag provided but not defined: -vm
Usage of gopy:"
Not sure what the issue could be as i'm not very familiar with Go, but any input would be appreciated.

**Comment by clouedoc** [comment]
I guess that you needed to put the flag after `build`

**Comment by rcoreilly** [comment]
assuming that was it..
