### ISSUE TITLE
Example of compiling with Setuptools

### ISSUE THREAD

**Issue by AlmogBaku** [go-python/gopy#278]
Hi all,
I suggest adding this example to the README. It took me about 1.5weeks to crack it :P
https://github.com/natun-ai/labsdk/blob/master/setup.py

Also, see this for cross-platform build
https://github.com/natun-ai/labsdk/blob/master/.github/workflows/wheels.yaml

**Comment by rcoreilly** [comment]
Thanks!  just added -- lmk if more info would be useful.
