### ISSUE TITLE
sed build error in windows with golang go version go1.19.4 windows/amd64 &&python3.11

### ISSUE THREAD

**Issue by cwing2019** [go-python/gopy#307]
C:\Users\Administrator\gotest>gopy build -output=out -vm=python3 github.com/go-python/gopy/_examples/hi
github.com/go-python/gopy/_examples/structs
github.com/go-python/gopy/_examples/cpkg
github.com/go-python/gopy/_examples/hi

--- Processing package: github.com/go-python/gopy/_examples/hi ---
no LibDir -- copy from IncDir: C:/Python311/libs
no LibPy -- set to: python311
no LibDir -- copy from IncDir: C:/Python311/libs
no LibPy -- set to: python311

--- building package ---
gopy build -output=out -vm=python3 github.com/go-python/gopy/_examples/hi
goimports -w hi.go
no LibDir -- copy from IncDir: C:/Python311/libs
no LibPy -- set to: python311
go build -mod=mod -buildmode=c-shared -o hi_go.pyd .
C:\Python311\python3.exe build.py
Doing windows sed hack to fix declspec for PyInit
cmd had error: exec: "sed": executable file not found in %PATH%  output:
o
2023/01/19 22:40:59 error dispatching command: exec: "sed": executable file not found in %PATH%

**Comment by theradius** [comment]
I solved this by downloading sed.exe from: https://unxutils.sourceforge.net/ and adding this to PATH.

**Comment by cwing2019** [comment]
using git 's sed also works in win11.
but no work no win10
