### ISSUE TITLE
Invalid #cgo CFLAGS / Invalid #cgo LDFLAGS on Windows for path with space

### ISSUE THREAD

**Issue by Igor-Kholupko** [go-python/gopy#349]
### Subject of the issue
Build operation fails in Windows when include/library path has spaces

### Environment
* Windows 11, Windows 10
* go version go1.21.5 windows/amd64
* github.com/go-python/gopy@0.4.8
* golang.org/x/tools@v0.16.0
* Python 3.10.5
* PyBindGen 0.22.1

### Prerequisites
* Python installed globally (ex. ```C:/Program Files/Python/Python310```)

### Steps to reproduce
* Run ```gopy build -output dist .```

### Actual behaviour
* Build failed
```
...
go build -mod=mod -buildmode=c-shared -o module_go.pyd .
cmd had error: exit status 1  output:
go: finding module for package github.com/go-python/gopy/gopyh
go: found github.com/go-python/gopy/gopyh in github.com/go-python/gopy v0.4.8
some-package/dist: invalid flag in #cgo CFLAGS: Files/Python/Python310/Include
```

### Expected behaviour
* Successful build 

### Caused
* Problem caused by incorrectly formatted cgo stub file, path in CFLAGS/LDFLAGS must be quoted:
```
#cgo CFLAGS: -IC:/Program Files/Python/Python310/Include -Wno-error -Wno-implicit-function-declaration -Wno-int-conversion
#cgo LDFLAGS: -LC:/Program Files/Python/Python310/libs -lpython310
```

**Comment by rcoreilly** [comment]
I don't use windows -- but 08d1f14 seems to not fail on mac -- just using regular " quotes.  feel free to submit a PR if this doesn't actually fix it.
