### ISSUE TITLE
gopy: consider support of a CFFI backend

### ISSUE THREAD

**Issue by sbinet** [go-python/gopy#48]
prompted by: https://www.reddit.com/r/Python/comments/3ig3ww/building_python_modules_with_go_15_xpost_from/cugc9ri

it could be interesting to have a `CFFI` backend for `pypy`'s benefit.
maybe simpler to just tap into `cppyy` ?

see https://github.com/jbuberel/buildmodeshared/tree/master/gofrompython for a `CFFI`-based example

**Comment by corona10** [comment]
I am working on this issue.
