### ISSUE TITLE
[build failed] too many errors

### ISSUE THREAD

**Issue by gotlium** [go-python/gopy#49]
$ go get github.com/go-python/gopy
	# github.com/go-python/gopy/bind
	/usr/src/go/src/github.com/go-python/gopy/bind/gencpy_struct.go:386: cannot use m (type *types.Func) as type *types.Package in argument to types.ObjectString
	/usr/src/go/src/github.com/go-python/gopy/bind/gencpy_type.go:363: cannot use m (type *types.Func) as type *types.Package in argument to types.ObjectString
	/usr/src/go/src/github.com/go-python/gopy/bind/gencpy_type.go:385: cannot use m (type *types.Func) as type *types.Package in argument to types.ObjectString
	/usr/src/go/src/github.com/go-python/gopy/bind/gengo.go:245: cannot use arg.GoType() (type types.Type) as type *types.Package in argument to types.TypeString
	/usr/src/go/src/github.com/go-python/gopy/bind/gengo.go:246: cannot use func literal (type func(*types.Package) string) as type types.Type in argument to types.TypeString:
		func(*types.Package) string does not implement types.Type (missing String method)
	/usr/src/go/src/github.com/go-python/gopy/bind/gengo.go:791: cannot use m (type *types.Func) as type *types.Package in argument to types.ObjectString
	/usr/src/go/src/github.com/go-python/gopy/bind/package.go:288: cannot use m (type *types.Func) as type *types.Package in argument to types.ObjectString
	/usr/src/go/src/github.com/go-python/gopy/bind/symtab.go:173: cannot use s.GoType() (type types.Type) as type *types.Package in argument to types.TypeString
	/usr/src/go/src/github.com/go-python/gopy/bind/symtab.go:174: cannot use func literal (type func(*types.Package) string) as type types.Type in argument to types.TypeString:
		func(*types.Package) string does not implement types.Type (missing String method)
	/usr/src/go/src/github.com/go-python/gopy/bind/symtab.go:263: cannot use t (type types.Type) as type *types.Package in argument to types.TypeString
	/usr/src/go/src/github.com/go-python/gopy/bind/symtab.go:263: too many errors

    $ go version
    go version go1.5 darwin/amd64

    $ uname -a
    Darwin gotlium.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64

**Comment by sbinet** [comment]
hum, you probably have an old version of `golang.org/x/tools/go/types`.

try:
```sh
$ go get -u github.com/go-python/gopy
```

(which should update the dependencies of `gopy`)

**Comment by gotlium** [comment]
$ go get -u github.com/go-python/gopy
	# github.com/go-python/gopy/bind
	/usr/src/go/src/github.com/go-python/gopy/bind/gencpy_struct.go:386: cannot use m (type *types.Func) as type *types.Package in argument to types.ObjectString
	/usr/src/go/src/github.com/go-python/gopy/bind/gencpy_type.go:363: cannot use m (type *types.Func) as type *types.Package in argument to types.ObjectString
	/usr/src/go/src/github.com/go-python/gopy/bind/gencpy_type.go:385: cannot use m (type *types.Func) as type *types.Package in argument to types.ObjectString
	/usr/src/go/src/github.com/go-python/gopy/bind/gengo.go:245: cannot use arg.GoType() (type types.Type) as type *types.Package in argument to types.TypeString
	/usr/src/go/src/github.com/go-python/gopy/bind/gengo.go:246: cannot use func literal (type func(*types.Package) string) as type types.Type in argument to types.TypeString:
		func(*types.Package) string does not implement types.Type (missing String method)
	/usr/src/go/src/github.com/go-python/gopy/bind/gengo.go:791: cannot use m (type *types.Func) as type *types.Package in argument to types.ObjectString
	/usr/src/go/src/github.com/go-python/gopy/bind/package.go:288: cannot use m (type *types.Func) as type *types.Package in argument to types.ObjectString
	/usr/src/go/src/github.com/go-python/gopy/bind/symtab.go:173: cannot use s.GoType() (type types.Type) as type *types.Package in argument to types.TypeString
	/usr/src/go/src/github.com/go-python/gopy/bind/symtab.go:174: cannot use func literal (type func(*types.Package) string) as type types.Type in argument to types.TypeString:
		func(*types.Package) string does not implement types.Type (missing String method)
	/usr/src/go/src/github.com/go-python/gopy/bind/symtab.go:263: cannot use t (type types.Type) as type *types.Package in argument to types.TypeString
	/usr/src/go/src/github.com/go-python/gopy/bind/symtab.go:263: too many errors

**Comment by gotlium** [comment]
thanks, now all is working after ```x/tools/go/types`` removed.

**Comment by sbinet** [comment]
great!

it is somewhat unnerving `go get -u` didn't do the trick, though...
