### ISSUE TITLE
distribution difference: python2.pc vs. python2.7.pc

### ISSUE THREAD

**Issue by twotwotwo** [go-python/gopy#51]
Testing on an Amazon Linux development instance, I noticed it puts Python 2.7's package configuration in `python2.7.pc`, whereas Ubuntu calls it `python2.pc`. I was able to bind the `hi` example just by changing the `python2` in `gengo.go` to `python2.7`. I'm guessing Amazon Linux inherits this quirk from its more-widely-used upstreams (CentOS/RHEL), but haven't checked that.

gopy could test for the existence of `/usr/lib64/python2.7.pc` or `/usr/lib/python2.7.pc`, and, if one of those is present, put python2.7 instead of python2 in the `#cgo pkg-config` line in the generated go file.

(It might help some new users if `gopy` suggested how to install Python headers and pkg-config if they appeared to be missing after a failed build. Some `gopy` users may be building their first extension.)

**Comment by sbinet** [comment]
could you give daf017b a spin?

**Comment by twotwotwo** [comment]
Works perfectly! Thank you!
