### ISSUE TITLE
error dispatching command: gopy: invalid python version ()

### ISSUE THREAD

**Issue by prashanthellina** [go-python/gopy#66]
The package

```go
package dummy

/* DoSomething adds two numbers */
func DoSomething(a, b int) int {
        return a + b
}
```

Fails with

```bash
2015/09/10 15:38:23 error dispatching command: gopy: invalid python version ()
```

```bash
python -V
Python 2.7.6
```

**Comment by phil-mansfield** [comment]
To expand on this, this occurs when calling `gopy gen` without specifying a `lang` flag. The behavior for `gopy bind` is to default to `lang="py2"`,  meaning that the behavior between the two modes is not consistent.

**Comment by prashanthellina** [comment]
Ah. I just tried `gen` with `lang=py2` and it worked. As you said, `bind` works without specifying explicitly.

**Comment by sbinet** [comment]
could you give `gopy-gen-issue-66` a try?

**Comment by phil-mansfield** [comment]
Yes, this works.

Don't forget to update the README, too.

**Comment by sbinet** [comment]
right. "almost" forgot about that, thanks :)
