### ISSUE TITLE
Does not seem to compile locally

### ISSUE THREAD

**Issue by ctownsen357** [go-python/gopy#68]
I've walked through the command line build process using your example that points to the git repo without any problems but as soon as I try to perform a bind locally then I get the following error:

hi.go:18:2: open /tmp/gopy-784930588/hi: no such file or directory

This is when I perform the following command:
gopy bind -output="out" /path/to/hi

I've tried multiple path options and I can see the files in /tmp/gopy-* but for some reason it seems to be looking for a subdirectory named hi.  

I'm looking through the code to see if I can determine either what I'm doing wrong or if there is a bug I can help fix.

Regards (I'm running Ubuntu 14.04 LTS).

**Comment by sbinet** [comment]
Hi Chris,

Could you post instructions to reproduce?
I am not completely clear on what you tried exactly.
Thanks.
-s

**Comment by ctownsen357** [comment]
Hi, thank you for the reply.  I installed gopy without incident and the command line example worked fine when it binds against your example on GitHub.

When I download a copy of hi.go or use a very simplified version I get the error.  To reproduce:
- Create a local folder like /usr/you/gopy_test
- cd to /usr/you/gopy_test
- create a sub directory hi
- copy hi.go to /usr/you/gopy_test/hi (or use the simplified version you provide in the docs)
- from /usr/you/gopy_test I tried to execute: gopy bind ./hi
- it starts the build process and then returns the error: hi.go:18:2: open /tmp/gopy-784930588/hi: no such file or directory

I have tried with a fully qualified path as well many other variant paths including trying to run it from the sub directory.

Is that enough info? Thank you so much for the help.

**Comment by sbinet** [comment]
Chris,

yes, that's enough info: I can reproduce the failure.
this seems to happen when `gopy_test/hi` is outside of `$GOPATH/src`.

I'll see whether I can at least the error more informative.

**Comment by ctownsen357** [comment]
OK, great, thank you! I was able to build when I copied things into the existing $GOPATH location.  What would be the appropriate addition to $GOPATH to have the project located in /home/you/gopy_test/hi? I've tinkered with appending to $GOPATH but without success.  

I can certainly get by with placing things in the existing $GOPATH/src directory but it would be convenient to append another location to $GOPATH, I just can't get it working at the original location when I append to $GOPATH.

Thank you again for the help!

**Comment by sbinet** [comment]
You would probably have to put 'gopytest' under '/home/you/src' and have GOPATH point at '/home/you'

Hth,
-s

**Comment by sbinet** [comment]
You would probably have to put 'gopytest' under '/home/you/src' and have GOPATH point at '/home/you'

Hth,
-s

**Comment by ctownsen357** [comment]
Thank you for the help Sebastien.

**Comment by sbinet** [comment]
reopening as I have now a CL with a better error message:

```
$ gopy bind ./hi
go install: no install location for directory /home/binet/tmp/ttt-gopy/hi outside GOPATH
	For more details see: go help gopath
2015/11/16 12:49:15 error installing [./hi]: exit status 1
2015/11/16 12:49:15 error dispatching command: gopy-bind: go/build.Import failed with path="./hi": exit status 1

```
