### ISSUE TITLE
Flask, Tornado, call into Go library with concurrent internal functions hang

### ISSUE THREAD

**Issue by ctownsen357** [go-python/gopy#74]
I have a case where a Go function that makes use of concurrent functions internally would hang when running in the context of a Flask REST API running with a Tornado server.  It would NOT hang when called directly from a Python script from the command line but the same Go function called from within the Flask/Tornado setup would hang when the concurrent code would run.  

I have since converted the entire REST API to Go but wanted to circle back and post this - will follow up with example code and see if I can dig in and help resolve.

**Comment by sbinet** [comment]
Does the concurrent code call back into cpython?
(If yes, then, I would suspect a deadlock involving the GIL, but that's just a hunch.)

**Comment by ctownsen357** [comment]
I've been away for a while, will work on the example soon.  No, the concurrent code does not call back into cpython.

**Comment by ctownsen357** [comment]
I've got a simple example coded up now - it consists of four very small files.  Four files simply to replicate what I had going on in the original project.  What would be the most appropriate way to share these? Create my own Git project or add them to a branch here? Or?

**Comment by sbinet** [comment]
you should be able to attach them to this issue (click on the "selecting them" link at the bottom of the issue text edition box)
or perhaps just post a gist link? https://gist.github.com/

**Comment by ctownsen357** [comment]
OK, thank you.  I'm new to Git and Github.  I see it now - right in front of my nose.  The attached file contains 3 Python files and 1 go source code.  

#### Here is how to replicate after extracting:
0. Install Python dependencies: tornado, flask, flask-restful
1. Build the go source with gopy to create gotest.so (I had to place this in a sub-folder named gotest)
    * make sure the resulting gotest.so file is at the same directory level as the python files or you'll have to modify the api2.py file
2. As a sanity check, run with the built in development/test web server and it will run correctly; this is to verify that the code will run end-to-end.  I didn't discover the problem until placing the app in a test environment that uses the Tornado server
    * execute the command python app.py
    * visit http://127.0.0.1:5000/api2 in your browser and you should see an integer output value
3. Run with the Tornado based server to take advantage of multiple processes and it will hang (this replicates the problem)
    * execute the command python apiserver.py
    * visit http://127.0.0.1:8000/api2 in your browser and you will see that it hangs indefinitely

I think you are right that it is the GIL and I'm unsure how to track it down further.  When I get the time I am planning on testing this wired up to run in Apache and NGINX to see if it hangs there too.  I have since converted the app to run entirely in Go but wanted to backtrack and post this as there may be others who encounter this - particularly in the Apache or NGINX environment - will post those results as I'm able.

Kind regards and thank you so much for such a great project.  Obviously a lot of talented work went into it.


[goflask.zip](https://github.com/go-python/gopy/files/82792/goflask.zip)

**Comment by justinfx** [comment]
I don't believe that this is related to gopy at all. I have tested this using a library built with `c-shared` and loaded into python using ctypes. The same problem is present when you use the forking multiprocess tornado server:

https://gist.github.com/justinfx/ab9fa42b0df19dc2c1f6

```shell
$ go build -buildmode=c-shared -o gotest.so gotest.go
```

I'm guessing it has to do with the general problem of combining threading and forking in the same process. Go is threaded, and then you fork the process using python's tornado server. Maybe there are bad mutexes being duped and all kinds of other stuff in the Go runtime that can't handle being forked.

Now... if I were to move the loading of the Go code into the handler, this ensures that it will load properly for each forked process, instead of having it done once in the main process, which is then forked.

```python
from ctypes import CDLL

class api2(Resource):

    GOTEST = None

    def get(self):
        if self.__class__.GOTEST is None:
            self.__class__.GOTEST = CDLL("gotest.so")
        
        return self.GOTEST.GetValWithConcurrency()
```

**Comment by ctownsen357** [comment]
Thank you for taking the time to look at that and figure out a solution; makes sense and explains why it works in the development server and not under Tornado.

**Comment by sbinet** [comment]
@justinfx Thanks for the detective work.
it all makes sense.

I am not sure whether the use of `fork()` can be detected reliably (probably just capturing `getpid()` at `C.dlopen()` and then checking whether the value changed at (or a bit after) `init()`)

**Comment by justinfx** [comment]
No worries. Been monitoring the progress as this project is highly relevant
to my daily work.

Thanks for all the hard work you have done!
