### ISSUE TITLE
go-python does not execute a python module anymore if that module once raises an exception

### ISSUE THREAD

**Issue by shtripat** [go-python/gopy#78]
Having an issue where, we invoke a python code using go-python. If the python code raises some exception once, then onwards any call to that python module returns immediately from CallObject() with blank return value.

Sample code to invoke python looks as below

========================
var pyinit = false
func Init() (err error) {
	if !pyinit {
		if err = python.Initialize(); err == nil {
			pyinit = true
		}
	}
	return
}

type PyFunction struct {
	*python.PyObject
}

var mutex sync.Mutex
func Import(module string, functions ...string) (funcs map[string]*PyFunction, err error) {
	if err = Init(); err != nil {
		return
	}

	if pymod := python.PyImport_ImportModuleNoBlock(module); pymod == nil {
		err = errors.New(fmt.Sprintf("gopy:%s: module import failed", module))
	} else {
		funcs = make(map[string]*PyFunction)
		for _, name := range functions {
			if pyfunc := pymod.GetAttrString(name); pyfunc == nil {
				err = errors.New(fmt.Sprintf("gopy:%s:%s: function not found", module, name))
				return
			} else {
				funcs[name] = &PyFunction{pyfunc}
			}
		}
	}
	return
}

func (f *PyFunction) Call(args ...interface{}) {
   	var pyargs *python.PyObject

	if pyargs, err = ToPyObject(reflect.ValueOf(args)); err != nil {
		return
	}
	mutex.Lock()
	defer mutex.Unlock()
	name := python.PyString_AsString(f.GetAttrString("__name__"))
	if r = f.CallObject(pyargs); r == nil {
		err = errors.New(fmt.Sprintf("%s(): function failed at python side", name))
	}
 }

var funcNames = [...]string{
	"MyFunc",
}

var pyFuncs map[string]*PyFunction
func main() {
    	pyFuncs, err := gopy.Import("mypackage", funcNames[:]...)
        if err != nil {
		panic(err)
	}
       for {
           if pyFuncs["MyFunc"].Call(); err !=nil {
               // handle the error
           }
      }
}
========================

In above scenario say the python function mypackage.MyFunc raises an exception in some scenario. Then onwards, it never enters the python code at all and keeps showing the error "function failed at python side".

Not sure if we should re-load the python interpreter from go code once exception or something else.
Kindly suggest.

Regards,
Shubhendu

**Comment by sbinet** [comment]
sorry, that's the wrong project.

please resubmit on https://github.com/sbinet/go-python/issues/new

**Comment by shtripat** [comment]
Sorry, about confusion.
Raised one at the mentioned place
