### ISSUE TITLE
gopy: provide a thin shim around gopy+docker

### ISSUE THREAD

**Issue by sbinet** [go-python/gopy#79]
Right now, `go-python/gopy` provides a `docker` container to ease cross-compilation:

``` sh
$ cd github.com/go-python/gopy/_examples/hi
$ docker run --rm -v `pwd`:/go/src/in -v `pwd`:/out gopy/gopy app bind -output=/out in
$ file hi.so
hi.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
```

we could directly provide a (sub)command, say `gopy xbind`, which would automatically perform the `docker run` incantation with the correct arguments to `docker` and its volumes bindings.

**Comment by rcoreilly** [comment]
for old version, closing
