### ISSUE TITLE
How to generate bind for multiple packages at same folder?

### ISSUE THREAD

**Issue by JunfengJia** [go-python/gopy#84]
folder py has two modules:
a.go -> package a
b.go -> package b

use gopy bind jack/py failed with:
can't load package: package jack/py: found packages a (a.go) and b (b.go)

**Comment by sbinet** [comment]
`gopy` is definitely `Go` oriented: it tries to provide `Go` packages to `python` users.
as such, `gopy` follows `Go` idioms.

thus, having a single directory containing `Go` source files with different packages, won't work (as this is not supported by the `go` tool).

you should put each of these files in their own directory:

```sh
$> cd jack
$> mkdir py/a py/b
$> mv a.go ./py/a/.
$> mv b.go ./py/b/.
```
then, `gopy bind jack/py/a` should work, as should `gopy bind jack/py/b`.

(although, having the `/py/` part would be perhaps a bit confusing from the `Go` side. I would personally drop it.)

**Comment by sbinet** [comment]
(closing as invalid. feel free to re-open if you feel it should be somehow supported)

**Comment by JunfengJia** [comment]
Yes, actually, I workaround in same way, because python can put different module at same folder, and I try to port those python files into go, what I expect is I can put the so file at the same folder to make porting process smoothly. anyway, the bug can be closed, it just not convenient even it comes from go.
