### ISSUE TITLE
bind: make sure GODEBUG=cgocheck=0 for Go>=1.6

### ISSUE THREAD

**Issue by sbinet** [go-python/gopy#85]
right now, `gopy` isn't following the "new" stricter `cgo` rules.
make sure that (for Go>=1.6) the `GODEBUG` environment variable contains `cgocheck=0` so the generated python module won't crash.

if the environment variable is not set, print out what to do, and continue execution.

**Comment by corona10** [comment]
I am working on this issue 👍

**Comment by sbinet** [comment]
Closed by go-python/gopy#91
