### ISSUE TITLE
gopy,bind: add boilerplate code for cffi support

### ISSUE THREAD

**Issue by sbinet** [go-python/gopy#87]
this means:

- `gopy/gen.go`: add a new `"cffi"` language switch
- `gopy/bind/...`: add a new `cffiGen` type, modeled after `cpyGen`.

**Comment by corona10** [comment]
## What I did.

I summary here for few things that I research about generating cffi support.

For this research, I used `_example/simple.go` for proto-typing.
The first step, Generating go file by `gengo.go`. This is already implemented.
Then gopy should generate `_simple.so`  by `go build -buildmode=c-shared -o _simple.so simple.go`

Then cffigen.go generate this `build.py`.

```` python
from cffi import FFI

ffibuilder = FFI()

ffibuilder.set_source(
    '_gopysimple',
    None,
    extra_objects=["_simple.so"],
)

ffibuilder.cdef("""
typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef float GoFloat32;
typedef double GoFloat64;
typedef struct { const char *p; GoInt n; } GoString;

extern GoString _cgopy_GoString(char* p0);
extern char* _cgopy_CString(GoString p0);
extern void cgo_pkg_simple_init();
extern void cgo_check();
extern GoInt cgo_func_simple_Add(GoInt p0, GoInt p1);
extern void cgo_func_simple_Func();
""")

if __name__ == "__main__":
    ffibuilder.compile()
````

Second, It will also generate `simple.py` in this way.

```` python
from __future__ import absolute_import

import os
from _gopysimple import ffi

here = os.path.dirname(os.path.abspath(__file__))
lib = ffi.dlopen(os.path.join(here, "_simple.so"))

lib.cgo_check()

lib.cgo_pkg_simple_init()

def cffi_func_simple_Func():
    lib.cgo_func_simple_Func()

def cffi_func_simple_Add(p0, p1):
    return lib.cgo_func_simple_Add(p0, p1)

def Func():
    return cffi_func_simple_Func()

def Sum(p0, p1):
    return cffi_func_simple_Add(p0, p1)

````

Finally, gopy will run `python build.py` and then copy files which will be needed for users.

## Problems
- 
   ````c
   - typedef float _Complex GoComplex64;
   - typedef double _Complex GoComplex128;
   - __SIZE_TYPE__
   
   ````

   These types are not supported by **cffi** yet.

## Conclusion
- Leave unsupported features until `cffi` update it or find out other ways to support this. (e.g wrapping these types or finding some other ways).
- Research about ctypes?

**Comment by corona10** [comment]
Ctypes backend can generate this python script.
And we don't have to care about complex types.
But as my knowledge, it would be a little bit slower than `cffi` backend.

And it has compatible with py2/3 and pypy also 👍 

```` python
import os

from ctypes import cdll

here = os.path.dirname(os.path.abspath(__file__))
lib = cdll.LoadLibrary(os.path.join(here, "_simple.so"))

lib.cgo_check()
lib.cgo_pkg_simple_init()

def cffi_func_simple_Func():
    lib.cgo_func_simple_Func()

def cffi_func_simple_Add(p0, p1):
    return lib.cgo_func_simple_Add(p0, p1)

def Func():
    return cffi_func_simple_Func()

def Sum(p0, p1):
    return cffi_func_simple_Add(p0, p1)

````

**Comment by corona10** [comment]
@sbinet I was wrong We don't need to generate `build.py`. It was already done by `go build -buildmode=c-shared -o _simple.so `

**Comment by corona10** [comment]
@sbinet I will update after some test with CFFI.

**Comment by corona10** [comment]
@sbinet I will update it after some tests with CFFI.

**Comment by corona10** [comment]
@sbinet If you have times, Please take a look.

**Comment by sbinet** [comment]
it's true that cffi doesn't support "directly out of the box" complex types (what Go calls `complex64` and `complex128`).

but I don't think that's necessarily an issue.
there are 2 cases:

```go

func F1(c complex128) complex128 { ... }
func F2(v MyType) { ... }

type MyType struct {
 value complex128
}
```

wrapping `F1` will involve converting the python complex-double value into a `gopy` `complex128` equivalent struct value, pass it to the `cgo` function that `gopy` has generated with `gengo` that will convert that `gopy_complex128` value into the Go `complex128`.
and similarly for the return value of `F1`.

wrapping `F2` is more or less the same (and perhaps even simpler as the `value` field of `MyType` isn't necessarily exposed to the `python` side.

that's definitely more work for a builtin type as `complex{64,128}` but not different than handling user defined types.

(but it's possible I am missing something.)

**Comment by corona10** [comment]
@sbinet 
Thank you for reviewing.
Except `complex` types.
Just two case needed to fix for the cffi.
* `typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];`
    -> typedef char _check_for_64_bit_pointer_matching_GoInt[1]; or 
    -> typedef char _check_for_64_bit_pointer_matching_GoInt[-1];
* `__SIZE_TYPE__` -> `size_t`
There might be more things which I missed.

**Comment by sbinet** [comment]
the first `typedef` doesn't need to be exposed to the `cffi` side (this will be done under the covers by Go's toolchain)

the second one would be more like `uintptr_t` in spirit (`uintptr_t` is defined in `<stdint.h>`): `__SIZE_TYPE__` is what is typedef'd to `GoUintptr`.
although, I am not completely sure the expectations on the size of `uintptr_t` matches exactly the ones of `GoUintptr` in all cases and on all the platforms that Go supports (or will support.)

IIRC, `gopy` doesn't really support `GoUintptr` arguments just yet, anyway.

**Comment by corona10** [comment]
@sbinet 
Thanks! It helps me alot for what should I do for next steps.

**Comment by corona10** [comment]
- Working on this issue.
https://github.com/corona10/gopy/tree/cffi

- Good reference to read about the relation between Go and C.
https://bitbucket.org/binet/go-ctypes

**Comment by corona10** [comment]
@sbinet 

https://github.com/corona10/gopy/commit/232972532b23d53e10876adf4dbc2e04b55533fc

I have done some basic works for generating python file binding by cffi.

Here is the step, The target Go file will be a `simple.go`

1. Run `gopy bind --lang=cffi .`
2. It will generate `build_simple.py` and `simple.py`.
`simple.py` will be a wrapper python codes works with CFFI.
`build_simple.py` will be a build cffi related files which also designate what interface would be exposed by cffi.
3. Copy `_simple.so` `build_simple.py` and `simple.py` into the target folder.
4. And then it will run `python run build_simple.py` it will generate `gopy/__init__.py` and `gopy/simple.py` finally it remove itself.
5. Just run python and then `import simple` will works!

Please take a look. This task will be a basic flow for working with cffi support.
