### ISSUE TITLE
bind: consider generating code from an AST

### ISSUE THREAD

**Issue by sbinet** [go-python/gopy#88]
right now, each code generator (`CGo` with `goGen`, `CPython2` with `cpyGen`) generates code via a few `fmt.Fprintf(w, "foo")` statements.

consider whether each code generator shouldn't instead generate an AST representation of what they want to generate (one for `Go`, one for `C` and, eventually, one for `Python`) and then have the AST dump itself into an `io.Writer`.

this is what the `c2go` project is considering to do (for `Go`, that is):
- https://github.com/elliotchance/c2go/tree/future/69-go-ast
- https://github.com/elliotchance/c2go/pull/72

there is already an AST package for Go: `go/ast`.
there is also one for C: `github.com/cznic/cc`
there doesn't seem to be one for Python, though...

**Comment by corona10** [comment]
@sbinet 

How about using Antlr4 for Golang target?
https://github.com/antlr/antlr4/blob/master/doc/go-target.md.

Grammar files already exist for python2 and python3.
https://github.com/antlr/grammars-v4/tree/master/python2
https://github.com/antlr/grammars-v4/tree/master/python3

**Comment by sbinet** [comment]
it's an option.

I must say I am not very fond of it because this involves installing Antlr4 (and thus Java), at least for the `gopy` developer (not necessarily, I assume, for the casual `gopy` user, if we commit the generated parser into the `gopy` repo).
so we might break the nice `go get`-ability of `gopy`.

generating a parser for the python syntax shouldn't be too difficult (famous last words) given the grammars that you link to (and what they link to themselves).

**Comment by sbinet** [comment]
just for completeness:

- https://docs.python.org/2/reference/grammar.html
- https://docs.python.org/3/reference/grammar.html

**Comment by rcoreilly** [comment]
for old version, closing
