### ISSUE TITLE
gopy: add a CONTRIBUTE guide

### ISSUE THREAD

**Issue by sbinet** [go-python/gopy#90]
probably something along the lines of `Go`'s, `gonum`'s and/or `go-hep` contribute guides:
 https://go-hep.org/contributing/

**Comment by corona10** [comment]
@sbinet I will translate it to Korean 👍 (It was one of my proposal for GSoC, 
There are many companies that are interested in migrating to Go from Python-based codebase in Korea.)

**Comment by sbinet** [comment]
SGTM. I am afraid I won't be able to give a meaningful review though :)
